language: python

python: 3.5

deploy:
  provider: pypi
  distributions: sdist
  user: michaelaye
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: michaelaye/python_boilerplate
